AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Lint/Void:
  Exclude:
    # Some tests use blocks with nil to test iteration behaviour
    - test/*

Metrics/BlockLength:
  Exclude:
    - test/*

Metrics/ClassLength:
  Exclude:
    - test/*

Metrics/MethodLength:
  Exclude:
    - test/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

plugins:
  - rubocop-minitest
  - rubocop-rake
