#
# Ambassador objects are returned by our domain interface methods.
#
# They act as read-only wrappers for domain entities, forming a stable and immutable
# interface to expose selected attributes to the outside world. This protects the internal
# models from direct access and allows for safer internal evolution.
#
# YOU SHOULD NOT NEED TO CREATE TOO MANY OF THESE OBJECTS. BUT WHEN RETURNING A DOMAIN ENTITY
# THROUGH A DOMAIN INTERFACE METHOD IT MUST BE AN AMBASSADOR
# ------------------------------------------------------------------------------------------
#
# @example Defining a user ambassador
#   class UserAmbassador < Ambassador
#     expose :id, :email, :created_at
#   end
#
#   user = User.find(...)
#   ambassador = UserAmbassador.new(user)
#   ambassador.email # => "user@example.com" (frozen)
#   ambassador.cleo_bank_cards # => NoMethodError
#
class Ambassador
  self.@exposed_property_names: untyped

  @__entity__: untyped

  VERSION: "0.0.1"

  #
  # Raised when trying to expose an unsafe property
  class InvalidPropertyError < StandardError
    @property_name: untyped

    # @param property_name [String, Symbol]
    def initialize: (untyped property_name) -> void

    # @return [String]
    def message: () -> ::String
  end

  # Declares one or more methods that should be publicly exposed as read-only properties
  # Values returned from these methods are frozen.
  #
  # @param properties [Array<Symbol>] list of method names to expose
  # @return [void]
  #
  # @example
  #   class CleoBank::CardAmbassador < Ambassador
  #     expose :id, :email
  #   end
  def self.expose: (*untyped properties) -> untyped

  private

  # @return [Set<Symbol>] the set of all exposed property names
  def self.exposed_property_names: () -> untyped

  # @param property_name [Symbol]
  # @raise [InvalidPropertyError]
  # @return [void]
  def self.check_property_name_is_exposable!: (untyped property_name) -> untyped

  public

  # @param entity [Object] the internal domain object being wrapped
  def initialize: (untyped entity) -> void

  # @return [Object] the wrapped domain entity
  def entity: () -> untyped

  def ==: (untyped other) -> untyped

  # String representation showing exposed fields and their values.
  #
  # @return [String]
  def inspect: () -> ::String

  private

  def exposed_properties: () -> untyped
end
